name: YTAudioDownloader
options:
  bundleIdPrefix: com.davidpoka
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"

settings:
  DEVELOPMENT_TEAM: 6Z45F3A37G
  CODE_SIGN_STYLE: Automatic
  SWIFT_VERSION: "5.9"

targets:
  YTAudioDownloader-iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.davidpoka.ytaudiodownloader
      INFOPLIST_KEY_CFBundleDisplayName: "YT Audio"
      INFOPLIST_KEY_CFBundleIconName: "AppIcon"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 2
      MARKETING_VERSION: 1.0.0
      TARGETED_DEVICE_FAMILY: "1,2"
      "INFOPLIST_KEY_UISupportedInterfaceOrientations": "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      "INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad": "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

  YTAudioDownloader-macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources/Shared
      - path: Sources/macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.davidpoka.ytaudiodownloader
      INFOPLIST_KEY_CFBundleDisplayName: "YT Audio"
      INFOPLIST_KEY_CFBundleIconName: "AppIcon"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 2
      MARKETING_VERSION: 1.0.0
      ENABLE_APP_SANDBOX: YES
      CODE_SIGN_ENTITLEMENTS: Sources/macOS/YTAudioDownloader_macOS.entitlements
      INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.music"
